using LiteDB;

namespace Community.LiteDB.Aot.Mapping;

/// <summary>
/// Interface for entity mappers generated by source generator.
/// Provides serialization/deserialization between entity and BsonDocument.
/// </summary>
/// <typeparam name="T">Entity type</typeparam>
public interface IEntityMapper<T> where T : class
{
    /// <summary>
    /// Collection name in database (default: typeof(T).Name)
    /// </summary>
    string CollectionName { get; }
    
    /// <summary>
    /// ID field name in BSON document (default: "_id")
    /// </summary>
    string IdFieldName { get; }
    
    /// <summary>
    /// Serializes entity to BsonDocument
    /// </summary>
    BsonDocument Serialize(T entity);
    
    /// <summary>
    /// Deserializes BsonDocument to entity
    /// </summary>
    T Deserialize(BsonDocument document);
    
    /// <summary>
    /// Extracts ID value from entity
    /// </summary>
    BsonValue GetId(T entity);
    
    /// <summary>
    /// Sets ID value in entity (after insert with AutoId)
    /// </summary>
    void SetId(T entity, BsonValue id);
}
